// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorId } from "./AuthorId";
import type { FileMeta } from "./FileMeta";
import type { Link } from "./Link";

export type AuthorJson = { id: AuthorId, name: string, links: Array<Link>, thumb: FileMeta | null, updated: string, };
