// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorId } from "./AuthorId";
import type { FileMetaJson } from "./FileMetaJson";
import type { Link } from "./Link";
import type { PostMiniJson } from "./PostMiniJson";

export type AuthorFullJson = { posts: Array<PostMiniJson>, id: AuthorId, name: string, links: Array<Link>, thumb: FileMetaJson | null, updated: string, };
