// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostMiniJson } from "./PostMiniJson";

export type AuthorPostsJson = { posts: Array<PostMiniJson>, total: number, };
