// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorId } from "./AuthorId";
import type { FileMetaId } from "./FileMetaId";
import type { Link } from "./Link";

/**
 * A content creator or contributor in the system
 */
export type Author = { id: AuthorId, name: string, links: Array<Link>, thumb: FileMetaId | null, updated: string, };
