// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user comment that can be attached to a post with support for nested replies
 */
export type Comment = { user: string, text: string, replies?: Array<Comment>, };
