// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorId } from "./AuthorId";
import type { FileMetaId } from "./FileMetaId";
import type { PostId } from "./PostId";

/**
 * Metadata for a file in the system with hierarchical path organization
 */
export type FileMeta = { id: FileMetaId, filename: string, author: AuthorId, post: PostId, mime: string, extra: Record<string, any>, };
