// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetaId } from "./FileMetaId";

export type FileMetaJson = { id: FileMetaId, url: string, mime: string, extra: Record<string,any>, };
