// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named URL reference that can optionally use a proxy service
 *
 * # Safety
 * - Names must not be empty
 * - URLs must be valid url.
 *
 * # Examples
 * ```rust
 * use post_archiver::Link;
 *
 * let github = Link::new("GitHub", "https://github.com/user");
 * assert_eq!(github.name, "GitHub");
 * assert_eq!(github.url, "https://github.com/user");
 * ```
 */
export type Link = { name: string, url: string, };
