// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { Comment } from "./Comment";
import type { ContentJson } from "./ContentJson";
import type { FileMeta } from "./FileMeta";
import type { PostId } from "./PostId";
import type { Tag } from "./Tag";

export type PostJson = { id: PostId, author: Author, source: string | null, title: string, content: Array<ContentJson>, thumb: FileMeta | null, comments: Array<Comment>, updated: string, published: string, tags: Array<Tag>, };
