// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorJson } from "./AuthorJson";
import type { FileMetaJson } from "./FileMetaJson";
import type { PostId } from "./PostId";

export type PostMiniJson = { id: PostId, author: AuthorJson, title: string, thumb: FileMetaJson | null, updated: string, };
