// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { FileMeta } from "./FileMeta";
import type { PostId } from "./PostId";

export type PostMiniJson = { id: PostId, author: Author, title: string, thumb: FileMeta | null, updated: string, };
