// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicConfig = { 
/**
 * Example: https://static.example.com/archiver
 */
resource_url: string | null, 
/**
 * Example: https://images.example.com/archiver
 */
images_url: string | null, };
