// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorId } from "./AuthorId";
import type { SummaryAuthorJson } from "./SummaryAuthorJson";

export type SummaryJson = { version: string, postArchiverVersion: string, tags: number, authors: { [key in AuthorId]?: SummaryAuthorJson }, };
