// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostTagId } from "./PostTagId";

/**
 * A categorical label that can be applied to posts
 *
 * # Safety
 * - Tag names must not be empty
 * - Tag names should be kebab-case
 * - IDs must be unique across all tags
 */
export type Tag = { id: PostTagId, name: string, };
